In [0]:
from __future__ import print_function
import torch 

Contruct a 5 * 3 matrix. 

In [0]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)   # Unintialized Matrix
print(x)  

tensor([[3.5616e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3613e-05, 1.6428e-07, 2.1629e+23],
        [1.6805e-04, 6.6526e+22, 1.6504e-07],
        [2.1352e+20, 4.1070e-08, 4.9001e-04]])


Initialized Matrix

In [0]:
x  = torch.empty(4,4)
print(x)

tensor([[3.5615e-37, 0.0000e+00, 4.4842e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3613e-05, 1.6428e-07],
        [2.1629e+23, 1.6805e-04, 6.6526e+22, 1.6504e-07],
        [2.1352e+20, 4.1070e-08, 8.9062e-01, 7.3952e-01]])


Construct a matrix filled zeros and of dtype long.


In [0]:
x = torch.zeros(4, 4, dtype=float)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [0]:
x= torch.rand(4 ,4)
print(x)

tensor([[0.4603, 0.8574, 0.0479, 0.1079],
        [0.7111, 0.8876, 0.2566, 0.7957],
        [0.1869, 0.9967, 0.3544, 0.2387],
        [0.3424, 0.2598, 0.5146, 0.3904]])


Construct a tensor directly from data

In [0]:
x = torch.Tensor([1,3,4,6])
print(x)

tensor([1., 3., 4., 6.])


Create a tensor based on an existing tensor
Will it use same properties ?
Can It be altered ?

In [0]:
x = torch.randn_like(x)
print(x)

tensor([ 0.4520,  0.6834,  0.4817, -0.7501])


torch.Size is a tuple. So can be used as a tuple.

In [0]:
# Size of a tensor.
t = x.size()
t[0] # Use like tuple

4

Addition of two tensors. Syntax 1

In [0]:
y = torch.rand(4,4)
print(y)
z = x + y
print(z)

tensor([[0.9724, 0.5381, 0.9178, 0.8688],
        [0.3063, 0.6981, 0.8581, 0.3495],
        [0.2228, 0.8170, 0.0214, 0.2233],
        [0.0529, 0.9716, 0.2467, 0.3849]])
tensor([[ 1.4244,  1.2215,  1.3995,  0.1186],
        [ 0.7584,  1.3815,  1.3398, -0.4006],
        [ 0.6748,  1.5004,  0.5031, -0.5268],
        [ 0.5049,  1.6551,  0.7283, -0.3652]])


Addition: providing an output tensor as argument. Syntax 2

In [0]:
z = torch.add(x,y)
print(z)
zz = 0.0
zz = torch.add(z,z,out=zz) # input and output should be of same type.
print(zz)

tensor([[ 1.4244,  1.2215,  1.3995,  0.1186],
        [ 0.7584,  1.3815,  1.3398, -0.4006],
        [ 0.6748,  1.5004,  0.5031, -0.5268],
        [ 0.5049,  1.6551,  0.7283, -0.3652]])
tensor([[ 2.8488,  2.4431,  2.7990,  0.2372],
        [ 1.5167,  2.7630,  2.6795, -0.8012],
        [ 1.3497,  3.0009,  1.0062, -1.0537],
        [ 1.0098,  3.3101,  1.4567, -0.7304]], dtype=torch.float64)


Addition: in-place

In [0]:
z3 = torch.randn_like(zz)
z3.add_(z)
print(z3)

tensor([[ 1.2375, -1.0616,  1.1647,  1.3916],
        [ 0.2134,  1.0527,  2.3556, -0.6029],
        [-1.1222,  2.5167,  0.6341, -2.2155],
        [ 0.9203,  2.6994,  1.4644, -0.1393]], dtype=torch.float64)


Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [0]:
zz = zz.view(2,8)
print(zz)
zz = zz.view(-1,4)
print(zz)

tensor([[ 2.8488,  2.4431,  2.7990,  0.2372,  1.5167,  2.7630,  2.6795, -0.8012],
        [ 1.3497,  3.0009,  1.0062, -1.0537,  1.0098,  3.3101,  1.4567, -0.7304]],
       dtype=torch.float64)
tensor([[ 2.8488,  2.4431,  2.7990,  0.2372],
        [ 1.5167,  2.7630,  2.6795, -0.8012],
        [ 1.3497,  3.0009,  1.0062, -1.0537],
        [ 1.0098,  3.3101,  1.4567, -0.7304]], dtype=torch.float64)


## Numpy Bridge

torch.from_numpy

In [0]:
import numpy as np 

a32 = np.random.rand(3,2)
print(a32)

b = torch.from_numpy(a32)

a32  = np.add(a32 , 1, out = a32)

print(a32, end=  '\n')

print(b)

[[0.74868454 0.82190141]
 [0.51554538 0.02377681]
 [0.94589892 0.9377241 ]]
[[1.74868454 1.82190141]
 [1.51554538 1.02377681]
 [1.94589892 1.9377241 ]]
tensor([[1.7487, 1.8219],
        [1.5155, 1.0238],
        [1.9459, 1.9377]], dtype=torch.float64)
